data_path: /home/hong/ws/twc-stable-pushnet/src/data

# Inference Configuration
planner:
  gripper_width: 0.08
  height: 0.015
  num_push_directions: 4 
  visualize: False
  learning_base: True
  image_type: 'masked'

depth_based:
  friction_coefficient: 1

network:
  model_name: "2023-10-15-2157_zivid"
  network_threshold: 0.2

hybrid:
  grid_size: 0.05  # unit: m
  dtheta:  5  # unit: deg

# Train Configuration
file_zero_padding_num: 7
base_lr: 0.0001
decay_rate: 0.95
train_l2_regularizer: 0.0005
batch_size: 64
num_epochs: 10
momentum_rate: 0.9
# model_name: "2023-08-25-0547"
network_threshold: 0.01
StablePushNet:
  image_height: 96
  image_width: 96
  batch_size: 64

# Anlyzation tool configuration for trained model
confusion:
  num_pushes: 1 # How many push cases you want to analyze
  num_data_points: 1000 # How many test samples you want to analyze

feature:
  num_data_points: 5000 # How many data points you want to analyze

network_output:
  num_pushes: 1 # How many push cases you want to analyze
